# Generated by Django 5.2.1 on 2025-05-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_staff',
        ),
    ]
