# Generated by Django 5.2.1 on 2025-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_utility', '0003_customusermodel_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='user',
        ),
    ]
