# Generated by Django 5.2.1 on 2025-05-22 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ward', '0002_remove_ward_allergies_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meals', models.JSONField()),
                ('naps', models.JSONField(null=True)),
                ('medication', models.JSONField(null=True)),
                ('day_highlight', models.CharField(max_length=150, null=True)),
                ('extra_needs', models.CharField(max_length=100, null=True)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ward.ward')),
            ],
        ),
    ]
