# Generated by Django 5.2.1 on 2025-05-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydeets', '0001_initial'),
        ('ward', '0002_remove_ward_allergies_allergies'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailydeets',
            constraint=models.UniqueConstraint(fields=('date', 'ward_id'), name='unique_ward_date'),
        ),
    ]
