# Generated by Django 5.2.1 on 2025-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydeets', '0002_dailydeets_unique_ward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeets',
            name='general_mood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailydeets',
            name='special_behavior',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
