# Generated by Django 5.2.1 on 2025-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydeets', '0003_dailydeets_general_mood_dailydeets_special_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydeets',
            name='meals',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dailydeets',
            name='medication',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dailydeets',
            name='naps',
            field=models.JSONField(default=list, null=True),
        ),
    ]
