# Generated by Django 5.2.1 on 2025-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailydeets', '0004_alter_dailydeets_meals_alter_dailydeets_medication_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailydeets',
            table='daily_deets',
        ),
    ]
