# Generated by Django 5.2.1 on 2025-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffprofile',
            table='staff',
        ),
    ]
