# Generated by Django 5.2.1 on 2025-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffprofile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
