# Generated by Django 5.2.1 on 2025-05-16 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_population', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField()),
                ('Allergies', models.JSONField()),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ward.classes')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
