# Generated by Django 5.2.1 on 2025-05-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='Allergies',
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.CharField(max_length=50)),
                ('allergy_reaction', models.CharField(max_length=50)),
                ('allergy_severity', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')])),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ward.ward')),
            ],
        ),
    ]
