# Generated by Django 5.2.1 on 2025-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0002_remove_ward_allergies_allergies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergies',
            table='allergies',
        ),
        migrations.AlterModelTable(
            name='classes',
            table='classes',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='wards',
        ),
    ]
